In [1]:
import datetime
import requests

import pandas as pd
import numpy as np

## Golf 2021 Full Leaderboard

In [2]:
# Site URL
stat = 'officialAmount'
url = f'https://www.espn.com/golf/statistics/_/year/2021/sort/{stat}'

# Retrieve page with the request module
response = requests.get(url)

In [3]:
# Pull tables via Pandas
# Reformat column headers, re-index
tables = pd.read_html(url)
money_df = tables[0]
money_df = money_df.drop_duplicates().drop(0)
header = money_df.loc[1]
money_df.columns = header
money_df = money_df.drop(1).reset_index(drop=True).drop(columns=['RK'])
money_df

1,PLAYER,AGE,EVENTS,ROUNDS,CUTS MADE,TOP 10,WINS,CUP POINTS,EARNINGS
0,Jon Rahm,26,18,61,18,11,1,1823,"$6,111,433.00"
1,Bryson DeChambeau,27,17,60,17,6,2,1802,"$6,018,847.00"
2,Justin Thomas,28,18,64,18,5,1,1708,"$5,907,945.00"
3,Patrick Cantlay,29,19,60,19,5,2,2014,"$5,620,030.00"
4,Harris English,31,21,72,20,7,2,1889,"$5,529,727.00"
5,Jordan Spieth,27,20,68,18,8,1,1742,"$5,016,964.00"
6,Louis Oosthuizen,38,16,54,16,6,0,1438,"$4,958,779.00"
7,Xander Schauffele,27,17,56,17,7,0,1579,"$4,942,637.00"
8,Collin Morikawa,24,18,60,16,7,1,1536,"$4,880,768.00"
9,Jason Kokrak,36,21,68,18,5,2,1573,"$4,803,058.00"
10,Viktor Hovland,23,19,63,18,6,1,1630,"$4,642,914.00"
11,Brooks Koepka,31,15,48,14,7,1,1450,"$4,631,711.00"
12,Cameron Smith,27,19,62,18,6,1,1411,"$4,325,445.00"
13,Dustin Johnson,37,15,52,14,5,1,1349,"$4,195,761.00"
14,Hideki Matsuyama,29,22,75,20,2,1,1336,"$3,984,819.00"
15,Scottie Scheffler,25,24,78,23,7,0,1262,"$3,952,564.00"
16,Patrick Reed,30,19,64,19,6,1,1332,"$3,907,658.00"
17,Sam Burns,24,21,64,18,6,1,1461,"$3,826,300.00"
18,Billy Horschel,34,20,66,19,5,1,1234,"$3,802,410.00"
19,Joaquin Niemann,22,22,82,22,5,0,1435,"$3,694,902.00"
20,Abraham Ancer,30,22,78,21,6,0,1371,"$3,691,996.00"
21,Rory McIlroy,32,16,54,15,6,1,1214,"$3,682,855.00"
22,Tony Finau,31,21,66,20,7,0,1239,"$3,607,064.00"
23,Daniel Berger,28,17,60,16,6,1,1235,"$3,497,086.00"
24,Corey Conners,29,24,84,21,7,0,1134,"$3,432,629.00"
25,Stewart Cink,48,20,70,20,3,2,1431,"$3,409,527.00"
26,Max Homa,30,24,70,19,5,1,1196,"$3,313,691.00"
27,Sungjae Im,23,29,98,28,4,0,1131,"$3,246,527.00"
28,Lee Westwood,48,15,46,14,2,0,834,"$3,210,976.00"
29,Marc Leishman,37,20,62,19,4,1,1084,"$3,000,346.00"
30,Brian Harman,34,22,80,22,5,0,987,"$2,973,546.00"
31,Charley Hoffman,44,26,89,24,5,0,1127,"$2,915,972.00"
32,Si Woo Kim,26,26,80,23,4,1,1015,"$2,759,238.00"
33,Carlos Ortiz,30,24,78,20,3,1,1025,"$2,579,299.00"
34,Phil Mickelson,51,19,62,18,1,1,740,"$2,559,724.00"
35,K.H. Lee,29,28,86,24,2,1,937,"$2,557,633.00"
36,Paul Casey,43,16,56,15,6,0,769,"$2,547,796.00"
37,Cam Davis,26,21,74,21,3,1,1014,"$2,539,615.00"
38,Sergio Garcia,41,18,52,15,3,1,904,"$2,416,200.00"
39,Matt Jones,41,25,86,23,3,1,1022,"$2,400,685.00"

In [ ]:
# Initialize counter value for URLs
url_num = 1

# Loop through pages based on number of pages. Each page URL starts with ranked 1, 41, 81, etc.
# I could not figure out a way to clic the "next" button, as there was no value or button tag
# To revisit this using Splinter at a later time
for i in range(1,15):
    
    # Visit new URL page for stat
    url_num = url_num + 40
    url = f'https://www.espn.com/golf/statistics/_/count/{url_num}'
    
    # Create table into dataframe, drop first row, assign new column headers
    # Merge with main money_df DataFrame
    tables = pd.read_html(url)
    temp_df = tables[0]
    temp_df = temp_df.drop_duplicates().drop(0)
    header = temp_df.loc[1]
    temp_df.columns = header
    temp_df = temp_df.drop(1).reset_index(drop=True).drop(columns=['RK'])
    money_df = money_df.append(temp_df)

In [ ]:
# Drop any duplicates to main dataframe and reset the index
money_df = money_df.drop_duplicates().reset_index(drop=True)
money_df